version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_final
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db
      MYSQL_USER: test_user 
      MYSQL_PASSWORD: qwerty
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mysql-network:
        aliases:
          - mysql

  app:
    build: .
    container_name: python_final
    depends_on:
      - mysql
    restart: always
    ports:
      - '8000:8000'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
